[module]
[[module.imports]]
  path = 'github.com/LordMathis/hugo-theme-nightfall'

baseURL = 'http://hugo-quickstart-template.netlify.com'
languageCode = 'en-us'
title = 'Netlify + Hugo Quickstart'
theme = 'nightfall'

