[module]
[[module.imports]]
  path = 'github.com/LordMathis/hugo-theme-nightfall'
  
[[module.imports]]  
  path = 'github.com/sass/dart-sass-embedded'

baseURL = 'https://liopol2blog.netlify.app/'
languageCode = 'en-us'
title = 'Blog'
theme = 'nightfall'

